In [ ]:
Solution 1:-

In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list object, whereas the
variable array_list is a NumPy ndarray object. To print the data types of both the variables, we can use the type() function:

In [4]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Solution 2:-

In [ ]:
To print the data type of each and every element of both the variables list_ and array_list, we can use the dtype attribute of the array:

In [5]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [6]:
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Solution 3:-

In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list. When we create the 
array using the dtype argument with the value 'int', the elements of the original list are cast to integers. To print the data types 
of each and every element present in both the variables list_ and arra_list, we can use the dtype attribute of the array:

In [7]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [8]:
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Solution 4:-

In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Solution 5:-

In [12]:
zeros_array = np.zeros((3, 3))

print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Solution 6:-

In [13]:
identity_matrix = np.identity(5)

print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
